name: Configure Azure environment

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  id-token: write

env:
  AZURE_RESOURCE_GROUP: cd-with-actions-nodeapp
  AZURE_APP_PLAN: actions-deployment-nodeapp-azure
  AZURE_LOCATION: southcentralus
  AZURE_WEBAPP_NAME: irvv17-deployment-nodeapp-azure

jobs:
  setup-up-azure-resources:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'spin up environment')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Create Azure resource group
        if: success()
        run: |
          az group create --location "$AZURE_LOCATION" --name "$AZURE_RESOURCE_GROUP" --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      - name: Create Azure app service plan
        if: success()
        run: |
          az appservice plan create --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_APP_PLAN" --is-linux --sku F1 --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      - name: Create webapp resource
        if: success()
        run: |
          az webapp create --resource-group "$AZURE_RESOURCE_GROUP" --plan "$AZURE_APP_PLAN" --name "$AZURE_WEBAPP_NAME" --deployment-container-image-name nginx --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      - name: Configure webapp to use GitHub Packages
        if: success()
        run: |
          az webapp config appsettings set --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_WEBAPP_NAME" --settings WEBSITES_PORT=80 --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}"
  destroy-azure-resources:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'destroy environment')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Destroy Azure environment
        if: success()
        run: |
          az group delete --name "$AZURE_RESOURCE_GROUP" --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}" --yes
